//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVirtual.Libraries.Lang {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LojaVirtual.Libraries.Lang.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este campo é obrigatório!.
        /// </summary>
        public static string MSG_E001 {
            get {
                return ResourceManager.GetString("MSG_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este campo deve ter no mínimo {1} caracteres!.
        /// </summary>
        public static string MSG_E002 {
            get {
                return ResourceManager.GetString("MSG_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este campo deve ter no máximo {1} caracteres!.
        /// </summary>
        public static string MSG_E003 {
            get {
                return ResourceManager.GetString("MSG_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este campo não é válido!.
        /// </summary>
        public static string MSG_E004 {
            get {
                return ResourceManager.GetString("MSG_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este campo não pode ficar em branco!.
        /// </summary>
        public static string MSG_E005 {
            get {
                return ResourceManager.GetString("MSG_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas estão diferentes!.
        /// </summary>
        public static string MSG_E006 {
            get {
                return ResourceManager.GetString("MSG_E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor enviado não está entre o mínimo ({1}) nem o máximo ({2}) necessários!.
        /// </summary>
        public static string MSG_E007 {
            get {
                return ResourceManager.GetString("MSG_E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A quantidade não pode ser 0. Remova o produto caso não deseje comprá-lo!.
        /// </summary>
        public static string MSG_E008 {
            get {
                return ResourceManager.GetString("MSG_E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desculpe! Não temos em estoque a quantidade desejada..
        /// </summary>
        public static string MSG_E009 {
            get {
                return ResourceManager.GetString("MSG_E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O serviço de entrega não foi selecionado..
        /// </summary>
        public static string MSG_E010 {
            get {
                return ResourceManager.GetString("MSG_E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail ou senha inválidos!.
        /// </summary>
        public static string MSG_E011 {
            get {
                return ResourceManager.GetString("MSG_E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum produto foi selecionado..
        /// </summary>
        public static string MSG_E012 {
            get {
                return ResourceManager.GetString("MSG_E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor informado já está registrado no banco!.
        /// </summary>
        public static string MSG_E013 {
            get {
                return ResourceManager.GetString("MSG_E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir Categorias que possuem outras categorias vinculadas: {0}.
        /// </summary>
        public static string MSG_E014 {
            get {
                return ResourceManager.GetString("MSG_E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir Categorias que possuem produtos vinculados: {0}.
        /// </summary>
        public static string MSG_E015 {
            get {
                return ResourceManager.GetString("MSG_E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro cadastrado com sucesso!.
        /// </summary>
        public static string MSG_S001 {
            get {
                return ResourceManager.GetString("MSG_S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro excluido com sucesso!.
        /// </summary>
        public static string MSG_S002 {
            get {
                return ResourceManager.GetString("MSG_S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro atualizado com sucesso!.
        /// </summary>
        public static string MSG_S003 {
            get {
                return ResourceManager.GetString("MSG_S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova senha gerada e enviada com sucesso!.
        /// </summary>
        public static string MSG_S004 {
            get {
                return ResourceManager.GetString("MSG_S004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro realizado com sucesso!.
        /// </summary>
        public static string MSG_S005 {
            get {
                return ResourceManager.GetString("MSG_S005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados atualizados com sucesso! ;).
        /// </summary>
        public static string MSG_S006 {
            get {
                return ResourceManager.GetString("MSG_S006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço de entrega atualizado com sucesso!.
        /// </summary>
        public static string MSG_S007 {
            get {
                return ResourceManager.GetString("MSG_S007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço de entrega removido com sucesso!.
        /// </summary>
        public static string MSG_S008 {
            get {
                return ResourceManager.GetString("MSG_S008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço de entrega cadastrado com sucesso!.
        /// </summary>
        public static string MSG_S009 {
            get {
                return ResourceManager.GetString("MSG_S009", resourceCulture);
            }
        }
    }
}
